name: Workflow for Continuous Integration with GitHub Actions

on:
  push:
    branches:
      - master

env:
  baseURL: http://localhost:3000

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Run unit tests
        run: npm run test

      - name: Start the application
        run: npm start

      - name: Save the app data
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: .next

      